### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [GAumala/blog#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by GAumala** [comment]
Hi! Thank you for showing interest in my blog. 

I don't know anything about feeds since I've never used them, but apparently it is easy to add one with Hakyll. I'll let you know when it is ready. 

My blog isn't exclusively about Haskell so I'm not sure if there's a simple way for you to filter non-Haskell posts though.

**Comment by tfausak** [comment]
Hakyll supports feeds out of the box! https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

I don't mind that your blog isn't entirely Haskell 😄

**Comment by GAumala** [comment]
Added [Atom](https://gaumala.com/atom.xml) and [RSS](https://gaumala.com/rss/posts.rss) feeds. I'll add links to those on the homepage later. Let me know if there are any issues.

**Comment by tfausak** [comment]
🎉 Great, thanks!
